# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9ec117d3d454999b6abdc66d2f55fd4def85b610f95531636eaec91ce3bdf9c36e907072b9e94a4e3fed491695ebaa58363890adbee1ab578b898328ca84a58

test:
  secret_key_base: e3df50d5864d9f0e68adaeb8f8c3e884529c157dc43a405c6cfaec04a3bcdd068e3ec3d94d738354f3824b5ac887c8ce89fa5cde1a57be8e6b8d97f71c0a8151

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
